### ISSUE TITLE
find points that we should change from the original site.

### ISSUE THREAD

**Issue by EriMiwa** [yoniakabecky/HTML_project1#3]

**Comment by yoniakabecky** [comment]
Ballet BC  https://balletbc.com/  

This site is pretty cool. i like zoom in/out design ;)

**Comment by EriMiwa** [comment]
@yoniakabecky thanks for finding out ideas!
in this case, images are used transition and transform effect. I think it's not difficult to implement.
these effects are impressive for showing images!
