### ISSUE TITLE
draw Top page wire frame

### ISSUE THREAD

**Issue by EriMiwa** [yoniakabecky/HTML_project1#4]

**Comment by EriMiwa** [comment]
Hi, sorry for being late to sending wire frame.
pls, let me know your ideas!
https://www.figma.com/file/EBBDozfdUbTvKgThgjSKPpIY/ballet-site?node-id=0%3A1

my opinions of improving points for the top page are below.
1. use images and movies bigger for showing school atmosphere.
2. title and text font change bigger, and make margin.
3. consider visual of mobile. (probablly most of user of this site search this site by mobile.)
4. design tone is the image of "elegance"  maybe like these color below..??
https://coolors.co/022b3a-1f7a8c-bfdbf7-e1e5f2-ffffff
https://coolors.co/15181b-222529-e8e8e8-f3f3f3-ffffff
https://coolors.co/app/eabfb7-7b8b9b-fffeff-0e0c0c-9a8596
.https://coolors.co/fdd4da-73545a-f6ede4-fefbfb-1f1627

**Comment by dunlop1** [comment]
sorry guys, i shared some ideas about design and header in figma
